apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: shop-demo
resources:
  - ../../base
labels:
  - pairs:
      app.kubernetes.io/part-of: kubecouncil-demo
      app.kubernetes.io/managed-by: kustomize
images:
  - name: kubecouncil-demo
    newName: asia-northeast1-docker.pkg.dev/findydevops/kubecouncil/kubecouncil-demo
    newTag: 4e1f6a84c445
