apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: gateway
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: gateway
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: checkout
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: checkout
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: payment
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: payment
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: recommendation
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: recommendation
