apiVersion: v1
kind: Service
metadata:
  name: gateway
spec:
  selector:
    app.kubernetes.io/name: gateway
  ports:
    - name: http
      port: 80
      targetPort: http
---
apiVersion: v1
kind: Service
metadata:
  name: checkout
spec:
  selector:
    app.kubernetes.io/name: checkout
  ports:
    - name: http
      port: 80
      targetPort: http
---
apiVersion: v1
kind: Service
metadata:
  name: payment
spec:
  selector:
    app.kubernetes.io/name: payment
  ports:
    - name: http
      port: 80
      targetPort: http
---
apiVersion: v1
kind: Service
metadata:
  name: recommendation
spec:
  selector:
    app.kubernetes.io/name: recommendation
  ports:
    - name: http
      port: 80
      targetPort: http
---
apiVersion: v1
kind: Service
metadata:
  name: analytics-worker
spec:
  selector:
    app.kubernetes.io/name: analytics-worker
  ports:
    - name: http
      port: 80
      targetPort: http
