apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../bootstrap/namespaced
  - ../../../demo
  - ../../base
  - ../../cluster
  - managed-certificate.yaml
  - runtime-config.yaml
patches:
  - path: ingress-tls-patch.yaml
